import pandas as pd

class Bianli_count:
    hydata = pd.read_csv('..\\..\\processed_csv\\processed_one\\IndirectJuvDetail_1.csv', sep=',', low_memory=False, header=0)
    hydata = hydata.drop(0, axis=0)
    hydata2 = pd.read_csv('..\\..\\processed_csv\\processed_one\\IndirectJuvDetail_2.csv', sep=',', low_memory=False, header=0)
    hydata2 = hydata2.drop(0, axis=0)
    hydata = hydata.append(hydata2, ignore_index=True)
    hydata3 = pd.read_csv('..\\..\\processed_csv\\processed_one\\IndirectJuvDetail_3.csv', sep=',', low_memory=False, header=0)
    hydata3 =hydata3.drop(0, axis=0)
    hydata = hydata.append(hydata3, ignore_index=True)
    hydata4 = pd.read_csv('..\\..\\processed_csv\\processed_one\\IndirectJuvDetail_4.csv', sep=',', low_memory=False, header=0)
    hydata4 = hydata4.drop(0, axis=0)
    hydata = hydata.append(hydata4, ignore_index=True)
    hydata5 = pd.read_csv('..\\..\\processed_csv\\processed_one\\IndirectJuvDetail_5.csv', sep=',', low_memory=False, header=0)
    hydata5 = hydata5.drop(0, axis=0)
    hydata = hydata.append(hydata5, ignore_index=True)
    hydata6 = pd.read_csv('..\\..\\processed_csv\\processed_one\\IndirectJuvDetail_6.csv', sep=',', low_memory=False, header=0)
    hydata6 = hydata6.drop(0, axis=0)
    hydata = hydata.append(hydata6, ignore_index=True)
    hydata7 = pd.read_csv('..\\..\\processed_csv\\processed_one\\IndirectJuvDetail_7.csv', sep=',', low_memory=False, header=0)
    hydata7 = hydata7.drop(0, axis=0)
    hydata = hydata.append(hydata7, ignore_index=True)
    hydata8 = pd.read_csv('..\\..\\processed_csv\\processed_one\\IndirectJuvDetail_8.csv', sep=',', low_memory=False, header=0)
    hydata8 = hydata8.drop(0, axis=0)
    hydata = hydata.append(hydata8, ignore_index=True)
    hydata.to_csv('..\\..\\processed_csv\\processed_two\\IndirectJuvDetail.csv', index=0, sep=',')
    M = hydata['SITEID'].value_counts()
    dict_m = {'SITEID': M.index, 'cishu': M.values}
    df_m = pd.DataFrame(dict_m)
    N = pd.read_csv('..\\..\\processed_csv\\processed_one\\wangba.csv', sep=',', low_memory=False, header=0)
    hydata = pd.merge(N, df_m, how='left', left_on=['SITEID'], right_on=['SITEID'])
    hydata.fillna(0, inplace=True)
    hydata = hydata.drop(['Unnamed: 4'], axis=1)
    hydata['cishu'] = hydata['cishu'].astype(int)
    hydata = hydata[hydata['cishu'] >= 5]
    hydata.to_csv('..\\..\\processed_csv\\processed_two\\IndirectJuvTime.csv', index=0, sep=',')